Add DB storage
gulllak/java-filmorate pull request #5
Opened 2023-11-20 13:22 UTC by gulllak

2023-11-20 16:10 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
а где MPA?

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT * FROM films";
еще вы через join-ы должны подтянуть genres и mpa

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT * FROM films WHERE id = ?";
еще вы через join-ы должны подтянуть genres и mpa

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/InMemoryFilmStorage.java
> +    @Override
здесь их по идее имплементировать не надо) вы работаете с базой данных

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/impl/LikeDbStorage.java
> +    public List<Integer> getPopularFilm(int count) {
1) это должно быть filmStorage
2) почему List<Integer>, должно быть List<Film>
3)getPopularFilms

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/impl/LikeDbStorage.java
> +        String sqlQuery = "SELECT f.ID, COUNT(l.user_id) AS col " +
надо возвращать популярные фильмы

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/InMemoryUserStorage.java
> +        for (int friendId : getUserById(id).getFriends()) {
тут одна строчка всего
return new ArrayList(getUserById(id).getFriends());

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/InMemoryUserStorage.java
> +            commonFriends.add(getUserById(userId));
а если commonFriendsId.size() будет большим - вы будете столько же запросов делать? перепишите чтобы был один запрос, возможно используя join-ы

2023-11-20 16:10 UTC, ErkinKasymaliev commented on src/main/resources/schema.sql
> +                                   id integer not null PRIMARY KEY auto_increment,
для id используйте bigint - аналог Long в Java

2023-11-20 16:22 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Genre> genres;
Поле MPA присутствует

2023-11-20 16:23 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT * FROM films";
В методе private Film createFilm(ResultSet rs, int rowNum) при сборке объекта подтягиваются Mpa и Genres

2023-11-20 16:27 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT * FROM films WHERE id = ?";
В методе private Film createFilm(ResultSet rs, int rowNum) при сборке объекта подтягиваются Mpa и Genres

2023-11-20 17:02 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/InMemoryFilmStorage.java
> +    @Override
Это старая реализация с хранением в Хэщмапе, интерфейс общий.

2023-11-20 17:04 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/impl/LikeDbStorage.java
> +    public List<Integer> getPopularFilm(int count) {
В filmStorage есть данный метод, он возвращается List<Film>, но перед этим происходит обращение к DAO likes чтобы собрать и передать в filmStorage idшники фильмов. Артем на вебинаре показывал эту реализацию.

2023-11-20 17:10 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/impl/LikeDbStorage.java
> +        String sqlQuery = "SELECT f.ID, COUNT(l.user_id) AS col " +
Это класс DAO LikeDbStorage, он из таблицы likes получает список id популярных фильмов и передает его в FilmDbStorage.

2023-11-20 17:12 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/impl/InMemoryUserStorage.java
> +            commonFriends.add(getUserById(userId));
Это старый класс для хранения в памяти, в хэшмапе.

2023-11-21 14:11 UTC, gulllak commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT * FROM films";
Исправлено, тяну все сразу.

2023-11-21 16:10 UTC, merged